---
version: 1.0.0
slug: intent-sentence-transformers
name: Sentence Transformers Agent
description: Sentence Transformers Agent
url: https://github.com/OHF-Voice/apps-experimental/tree/master/intent-sentence-transformers
arch:
  - amd64
  - aarch64
init: false
discovery:
  - wyoming
homeassistant_api: false
options:
  debug_logging: false
schema:
  debug_logging: bool
ports:
  "10500/tcp": null
homeassistant: 2023.11.0
